# This is a basic workflow to help you get started with Actions

name: Mirror R-Type [EPITECH]

on:
  push:

  
jobs:
   push_epitech:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            "git@github.com:EpitechPromo2026/B-CPP-500-LIL-5-2-bsrtype-azyanah.olaytan.git"
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
